version: '3.1'

services:
  mdtwallet-app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: mdtwallet/app:dev
    networks:
      - mdtwallet-api_api
    ports:
      - "8080:80"
    restart: always

networks:
  mdtwallet-api_api:
    external: true
