export default {

  UnknownError: 100,
  MissingParameters: 101,
  InvalidParameterValue: 102,
  InvalidJSONBody: 103,
  UnAuthorizedAccess: 104,
  ApplicationNotFound: 105,
  ApplicationInsufficientFund: 106,
  ValidationEndpointNotSet: 107,
  ValidationEndpointInvalid: 108,
  UserAlreadyExist: 109,
  UserNotExist: 110,
  UserPasswordNotSet: 111,
  UserEmailAddressNotConfirmed: 112,
  UserCredentialInvalid: 113,
  UserDisabled: 114,
  EmailConfirmCodeExpired: 115,
  EmailConfirmCodeInvalid: 116,
  EmailConfirmCodeUserNotFound: 117,
  EmailConfirmCodeAlreadyConfirmed: 118,
  ConfirmedPasswordNotMatch: 119,
  PasswordResetCodeExpired: 120,
  PasswordResetCodeInvalid: 121,
  AutoLoginValidationFailed: 122,
  APIKeyNotFound: 123,
  TaskNotFound: 124,
  TaskExpired: 125,
  TaskAlreadyFinished: 126,
  RedeemableItemNotFound: 127,
  RedeemableItemExpired: 128,
  RewardNotFound: 129,
  RewardExpired: 130,
  RewardAlreadyClaimed: 131,
  ProblemNotFound: 132,
  CommentsExceedMaxLength: 133,
  InvalidEmailAddress: 134,
  InvalidEthAddress: 135,
  InvalidPasscode: 136,
  InsufficientFund: 137,
  ContentTooLong: 138,
  InvalidPhoneNumberFormat: 139,
  SMSRequestTooFrequent: 140,
  OTPNotMatch: 141,
  OTPExpired: 142,
  InvalidExpiryTime: 143,
  TransactionNotFound: 144,
  TwofaAlreadyEnabled: 145,
  TwofaSecretNotGenerated: 146,
  TwofaTokenInvalid: 147,
  properties: {
    134: {
      messageId: 'message.transfer.invalid_email',
    },
    135: {
      messageId: 'message.transfer.invalid_ethaddress',
    },
    136: {
      messageId: 'message.transfer.insufficient_fund',
    },
  },
};

