const errorCode = {
  UnknownError: 100,
  MissingParameters: 101,
  InvalidParameterValue: 102,
  InvalidJSONBody: 103,
  UnAuthorizedAccess: 104,
  ApplicationNotFound: 105,
  ApplicationInsufficientFund: 106,
  ApplicationDisabled: 107,
  ValidationEndpointNotSet: 108,
  ValidationEndpointInvalid: 109,
  UserAlreadyExist: 110,
  UserNotExist: 111,
  UserPasswordNotSet: 112,
  UserEmailAddressNotConfirmed: 113,
  UserCredentialInvalid: 114,
  UserDisabled: 115,
  EmailConfirmCodeExpired: 116,
  EmailConfirmCodeInvalid: 117,
  EmailConfirmCodeUserNotFound: 118,
  EmailConfirmCodeAlreadyConfirmed: 119,
  ConfirmedPasswordNotMatch: 120,
  PasswordResetCodeExpired: 121,
  PasswordResetCodeInvalid: 122,
  AutoLoginValidationFailed: 123,
  APIKeyNotFound: 124,
  TaskNotFound: 125,
  TaskExpired: 126,
  TaskAlreadyFinished: 127,
  RedeemableItemNotFound: 128,
  RedeemableItemExpired: 129,
  RedeemLimitReached: 130,
  RewardNotFound: 131,
  RewardExpired: 132,
  RewardAlreadyClaimed: 133,
  ProblemNotFound: 134,
  CommentsExceedMaxLength: 135,
  InvalidEmailAddress: 136,
  InvalidEthAddress: 137,
  InvalidPasscode: 138,
  NewPasscodeSameAsOld: 139,
  ConfirmedPasscodeNotMatch: 140,
  InsufficientFund: 141,
  ContentTooLong: 142,
  InvalidPhoneNumberFormat: 143,
  PhoneNumberAlreadySet: 144,
  SMSRequestTooFrequent: 145,
  OTPNotMatch: 146,
  OTPExpired: 147,
  InvalidExpiryTime: 148,
  TransactionNotFound: 149,
  TwofaAlreadyEnabled: 150,
  TwofaSecretNotGenerated: 151,
  TwofaTokenInvalid: 152,
  PasscodeAlreadySet: 153,
  DeviceIsAlreadyRegistered: 154,
  AccessCodeIsNotValid: 155,
  AccessCodeIsUsed: 156,
};

errorCode.properties = {
  [errorCode.UserNotExist]: {
    messageId: 'message.error.userNotExist',
  },
  [errorCode.InvalidEmailAddress]: {
    messageId: 'message.transfer.invalid_email',
  },
  [errorCode.InvalidEthAddress]: {
    messageId: 'message.transfer.invalid_ethaddress',
  },
  [errorCode.InvalidPasscode]: {
    messageId: 'message.transfer.insufficient_fund',
  },
  [errorCode.RewardExpired]: {
    messageId: 'message.error.rewardExpired',
  },
  [errorCode.RewardAlreadyClaimed]: {
    messageId: 'message.error.rewardAlreadyClaimed',
  },
};

export default errorCode;
