version: '3.1'

services:
  mdtwallet-webapp:
    build:
      context: .
      dockerfile: docker/alpha/Dockerfile
    image: mdtwallet-webapp
    networks:
      - mdtwallet-webapp
    restart: always

networks:
  mdtwallet-webapp:
