<template>
  <section class="terms-of-use-screen">
    <h1>{{ $t('message.termsOfUse.title') }}</h1>
    <p>
      PLEASE SCROLL DOWN AND READ ALL OF THE FOLLOWING TERMS AND CONDITIONS OF THE MYMDT BETA SOFTWARE PROGRAM AGREEMENT ("AGREEMENT") CAREFULLY. IF YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, CONTINUE TO USE THE SERVICE. IF YOU DO NOT AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU WILL BE INELIGIBLE TO PARTICIPATE IN THE MYMDT BETA SOFTWARE PROGRAM. 

      MYMDT BETA SOFTWARE PROGRAM AGREEMENT 


      1. Participation in the MYMDT Beta Software Program. The purpose of the MYMDT Beta Software Program (“Beta Program”) is to make alpha, beta, seed, and other pre-release software, pre-release services, and related documentation, materials, and information (collectively, the “Pre-Release Software”) available to Beta Program participants from time to time for the purpose of providing MYMDT with feedback on the quality and usability of the Pre-Release Software. 
 
      MYMDT is a beta software developed by Measurable Foundation Limited (“MYMDT”).

      You understand and agree that participation in the Beta Program is voluntary and does not create a legal partnership, agency, or employment relationship between you and MYMDT. You understand that your participation in the Beta Program does not obligate MYMDT to provide you with any Pre-Release Software. MYMDT reserves the right to modify the terms, conditions, and policies of this Beta Program from time to time, and to revoke your participation in this Beta Program at any time. If MYMDT makes changes to the terms and conditions of this Agreement, then MYMDT will present such revised terms and conditions to you on the Beta Program web portal. 

      By participating in the Beta Program, You certify that you are of the legal age of majority in the jurisdiction in which you reside (at least 18 years of age in many countries) and you represent that you are legally permitted to join the Beta Program. This Agreement is void where prohibited by law and the right to become a Beta Program participant is not granted in such jurisdictions. Unless otherwise agreed or permitted by MYMDT in writing, you cannot share or transfer any software or other materials you receive from MYMDT in connection with being a Beta Program participant. 

      The MYMDT ID and password you use to login as a Beta Program participant cannot be shared in any way or with any one. You are responsible for maintaining the confidentiality of your MYMDT ID and password and for any activity in connection with your account. Notwithstanding the foregoing restrictions in this Section 1, if you are the parent or legal guardian of individuals between the ages of 13 and the legal age of majority in the jurisdiction in which you reside, you may allow such individuals to share your MYMDT ID and password for their use in connection with the Beta Program solely under your supervision and only in accordance with this Agreement. You are responsible for such individuals’ compliance with and violations of this Agreement and any other MYMDT agreements.

      2. Access to Pre-Release Software; Seeding Tools; and Additional Terms. You understand that MYMDT may make Pre-Release Software available to Beta Program participants for downloading online through the Apple’s App Store, or other App Store on Android systems (e.g., by manual download of a digital image, by providing software configuration profiles, etc.).

      From time to time, MYMDT, at its option, may also provide you with software or services as part of the Beta Program, including but not limited to scripts, code snippets, utilities, configuration profiles, sample code, troubleshooting applications and bug submission tools (“Seeding Tools”) as part of your participation in the Beta Program. 

      All use of such Pre-Release Software and Seeding Tools shall be pursuant to the terms and conditions of this Agreement and/or another license agreement accompanying such Pre-Release Software or Seeding Tools (collectively, “Pre-Release Software” and “Seeding Tools” shall be referred to as “MYMDT Software” for purposes of this Agreement). If the MYMDT Software is accompanied by a separate license agreement, you agree that the license agreement accompanying such MYMDT Software, in addition to Sections 5 and 6 of this Agreement, shall govern your use of the MYMDT Software. Any inconsistencies between the provisions of the license agreement accompanying the MYMDT Software and Sections 5 and 6 of this Agreement shall be governed by this Agreement. If there is no license agreement accompanying the MYMDT Software, your use of the MYMDT Software will be subject to the provisions of this Agreement. 

      3. License Grant and Restrictions. Subject to your compliance with this Agreement, MYMDT hereby grants you a personal, limited license to use the MYMDT Software solely for testing and evaluation purposes and only in connection with this Beta Program. Except as otherwise permitted under Section 15, this license does not grant you the right to use the MYMDT Software for any other purpose, or to disclose, reproduce, distribute, modify or create derivative works of the MYMDT Software. You agree not to decompile, reverse engineer, disassemble, decrypt, or otherwise attempt to derive the source code of any MYMDT Software (except as and only to the extent the foregoing restrictions are prohibited by applicable law, or to the extent as may be permitted by licensing terms governing use of opensourced components included with any such MYMDT Software). Unless otherwise permitted under Section 15 below, you certify that the MYMDT Software will only be used for testing and evaluation purposes in connection with the Beta Program, and will not be rented, sold, leased, sublicensed, assigned, distributed or otherwise transferred. MYMDT retains ownership of all MYMDT Software, and except as expressly set forth herein, no other rights or licenses are granted or to be implied under any MYMDT intellectual property. 

      4. Feedback; Contact from MYMDT. As part of the Beta Program, MYMDT will provide you with the opportunity to submit bug reports, questionnaires, enhancement requests, issue reports and/or support information (collectively, “Feedback”) to MYMDT. MYMDT may request this information from you through the Seeding Tools as well as by email, chat apps, web questionnaires, bug forms, and other mechanisms. By agreeing to this Agreement, you agree that MYMDT may contact you from time to time about the Beta Program, and you hereby consent to receive such communications. Except as otherwise set forth in Section 8, you agree that in the absence of a separate written agreement to the contrary, MYMDT will be free to use any Feedback you provide for any purpose. 

      5. Definition of Confidential Information. You agree that the Pre-Release Software and any information concerning the Pre-Release Software (including its nature and existence, features, functionality, and screen shots), the Seeding Tools, and any other information disclosed by MYMDT to you in connection with the Beta Program will be considered and referred to in this Agreement as “Confidential Information.” Information that otherwise would be deemed Confidential Information but (a) is generally and legitimately available to the public through no fault or breach of yours, (b) is generally made available to the public by MYMDT, (c) is independently developed by you without the use of any Confidential Information, (d) was rightfully obtained from a third party who had the right to transfer or disclose it to you without limitation, or (e) any third party software and/or documentation provided to you by MYMDT and accompanied by licensing terms that do not impose confidentiality obligations on the use or disclosure of such software and/or documentation will not be considered Confidential Information under this Agreement. All Confidential Information remains the sole property of MYMDT and you have no implied licenses or other rights in the Confidential Information not specified in this Agreement. 

      6. Nonuse and Nondisclosure of Confidential Information. Except as expressly permitted in this Section 6, you agree that you will not disclose, publish, or otherwise disseminate any Confidential Information to anyone other than individuals who are enrolled in the same individual seed as you, or as otherwise expressly permitted or agreed to in writing by MYMDT. You further agree to take reasonable precautions to prevent any unauthorized use, disclosure, publication, or dissemination of Confidential Information, including preventing access to or display of the MYMDT Software to third parties. You agree to use the Confidential Information solely for the permitted uses as set forth in this Agreement. You agree not to use Confidential Information otherwise for your own or any third party’s benefit without the prior written approval of an authorized representative of MYMDT in each instance. You hereby acknowledge that unauthorized disclosure or use of Confidential Information could cause irreparable harm and significant injury to MYMDT that may be difficult to ascertain. Accordingly, you agree that MYMDT will have the right to seek immediate injunctive relief to enforce obligations under this Agreement in addition to any other rights and remedies it may have.

      7. Precautions for the use of Pre-Release Software. You understand that to participate in seeds of Pre-Release Software you may need to remove certain pre-loaded, commercial MYMDT software from your computer and/or device in order to load the Pre-Release Software. You further understand that once you load such Pre-Release Software onto your computer and/or device, you may be unable to revert back to the pre-loaded, commercial release of the MYMDT software you were using prior to loading the Pre-Release Software or any earlier release of the Pre-Release Software. In addition, applications and services you have installed or been using may be unable to run or function in the same manner because of your use of the Pre-Release Software. 

      YOU ACKNOWLEDGE THAT BY INSTALLING SUCH PRE-RELEASE SOFTWARE ON YOUR MYMDT-BRANDED COMPUTERS AND/OR DEVICES, THESE COMPUTERS AND DEVICES MAY NOT BE CAPABLE OF BEING RESTORED TO THEIR ORIGINAL CONDITION AND THAT APPLICATIONS AND SERVICES MAY BE AFFECTED BY YOUR USE OF PRE-RELEASE SOFTWARE. FURTHER, YOU UNDERSTAND THAT DATA (INCLUDING DOCUMENTS) FROM SUCH APPLICATIONS OR SERVICES THAT YOU CREATE OR CHANGE WHILE USING THE PRE-RELEASE SOFTWARE MAY BE INCAPABLE OF BEING RESTORED OR RECOVERED. MYMDT SHALL NOT BE RESPONSIBLE FOR ANY COSTS, EXPENSES OR OTHER LIABILITIES YOU MAY INCUR AS A RESULT OF YOUR TESTING, INSTALLATION OR USE OF PRE-RELEASE SOFTWARE, INCLUDING BUT NOT LIMITED TO ANY DAMAGE TO ANY EQUIPMENT, SOFTWARE OR DATA OR ANY LOSS OF DATA OR INFORMATION ARISING FROM YOUR USE OF SUCH PRE-RELEASE SOFTWARE.

      In addition, the Pre-Release Software may contain errors or inaccuracies that could cause failures, corruption or loss of data and/or information from your computer and/or device or from your peripherals (including, without limitation, servers and printers) connected thereto. MYMDT strongly encourages you to back-up all data and information on your computer, devices and/or any peripherals prior to your participation in the Beta Program and before any individual seeds. The Pre-Release Software is not intended for use, and should not be used, in production or businesscritical systems. 

      8. Consent to Collection and Use of Data. 

      8.1 Pre-Release Versions of iOS. In order to test and help MYMDT, its partners, and third party developers improve their products and services, and unless you opt out as set forth below, you acknowledge that MYMDT and its subsidiaries and agents will be collecting, using, storing, processing and analyzing (collectively, “Collecting”) diagnostic, technical, and usage logs and information from your devices that are running such pre-release versions of iOS as part of this Beta Program. This information will be Collected in a form that does not personally identify you and may be Collected from such devices at any time, including when you sync to iTunes or automatically over a secure over-theair connection. The information that would be Collected includes, but is not limited to, general diagnostic and usage data, various unique device identifiers, details about hardware and operating system specifications, performance statistics, and data about how you use your device, applications and peripherals, and, if Location Services is enabled for Diagnostics, the location of the device at least once per day, the location where a call ends, and the wireless/cellular network coverage and current radio conditions at a particular location. Further, you agree that MYMDT may share such diagnostic, technical, and usage logs and information with partners and third party developers for purposes of allowing them to improve their products and services that operate on or in connection with MYMDT-branded products. By installing or using pre-release versions of iOS on your devices, you acknowledge and agree that MYMDT and its subsidiaries and agents have your permission to Collect all such information and use it as set forth above. If you do not agree to the foregoing, you may choose to turn off Diagnostics by going to Settings > General > About > Diagnostics & Usage on the device. You can also choose to turn off Location Services for Diagnostics at any time. To do so, open Settings, tap Location Services, tap System Services and turn off the Diagnostics switch on the device. 

      8.2 Other Pre-Release Software and services. In order to test and improve MYMDT’s products and services, and only if you choose to install or use other PreRelease Software or services provided as part of the Beta Program, you acknowledge that MYMDT and its subsidiaries and agents may be Collecting diagnostic, technical, usage and related information from other Pre-Release Software or services and from your computer, devices, peripherals or other hardware that uses such Pre-Release Software. You should carefully review the release notes and other information disclosed to you by MYMDT as part of the Beta Program prior to choosing whether or not to install or use any such other PreRelease Software or services. By installing or using such other Pre-Release Software or services, you acknowledge and agree that MYMDT and its subsidiaries and agents have your permission to Collect any and all such information and use it as set forth above. 

      8.3 System Logs and Diagnostic Files. In addition, as part of your participation in the Beta Program, you may have the option of manually attaching and/or using MYMDT’s Seeding Tools to attach detailed hardware and/or system diagnostic files (e.g., kernel logs, MYMDT System Profile logs, hang logs, crash logs, spin logs, install logs, application logs, etc.) from your computer and/or devices (“System Logs”) to send to MYMDT. Such System Logs may include personally identifiable information, including, without limitation, your account name, information regarding your contacts, calendar events, and email correspondence. Providing these System Logs is voluntary, but if you do provide them to MYMDT, then you acknowledge that MYMDT may use them for MYMDT's diagnostic purposes and to improve the Beta Program and MYMDT’s products and services. 

      8.4 Privacy Policy. Data collected pursuant to this Section 8 will be treated in accordance with MYMDT’s Privacy Policy.

      9. No Support and Maintenance; Future Products. During your participation in the Beta Program or in a particular seed, MYMDT is not obligated to provide you with any maintenance, technical or other support for the Pre-Release Software. If, at MYMDT’s option, such support is provided, it will be provided in addition to your normal warranty coverage for your computer and/or device. You agree to abide by any support rules and policies that MYMDT provides to you in order to receive such support. You acknowledge that MYMDT has no express or implied obligation to announce or make available a commercial version of the Pre-Release Software to anyone in the future. Should a commercial version be made available, it may have features or functionality that are different from those found in the Pre-Release Software licensed hereunder. 

      10. Discussion Forums. As part of the Beta Program, you may have the ability to participate in discussion forums provided by MYMDT about the PreRelease Software and other Confidential Information that MYMDT may make available to you. For purposes of such discussion forums, MYMDT is providing a limited exception to Section 6 by allowing you to discuss certain MYMDT Confidential Information received by you in connection with a particular seed with other seed participants who are in the same seed as you in the MYMDT designated discussion forum for such seed, and only within this discussion forum. Except for the limited purpose of discussions with other seed participants within such forums, you acknowledge and agree that this Agreement does not grant you the right to copy, reproduce, publish, blog, disclose, transmit, or otherwise disseminate any MYMDT Confidential Information. 

      11. No Warranty. The MYMDT Software provided hereunder may be designated as alpha, beta, development, pre-release, untested, or not fully tested versions. The MYMDT Software may be incomplete and may contain errors or inaccuracies that could cause failures, corruption and/or loss of data or information. You expressly acknowledge and agree that, to the extent permitted by applicable law, all use of the MYMDT Software is at your sole risk and that the entire risk as to satisfactory quality, performance accuracy and effort is with you. 

      MYMDT IS PROVIDING ALL CONFIDENTIAL INFORMATION, INCLUDING THE PRERELEASE SOFTWARE AND SEEDING TOOLS, TO YOU SOLELY ON AN “AS IS” BASIS AND WITHOUT ANY WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, PERFORMANCE, AND FITNESS FOR A PARTICULAR PURPOSE. 

      You acknowledge that MYMDT has not publicly announced the availability of the Pre-Release Software, that MYMDT has not promised or guaranteed to you that such Pre-Release Software will be announced or made available to anyone in the future, and that MYMDT has no express or implied obligation to you to announce or introduce the Pre-Release Software or any similar or compatible product, or to continue to offer access to the Pre-Release Software in the future. 12. Disclaimer of Liability. 

      YOU ASSUME ALL RISKS AND ALL COSTS ASSOCIATED WITH TESTING, INSTALLATION, OR USE OF THE PRERELEASE SOFTWARE AND SEEDING TOOLS PROVIDED UNDER THIS AGREEMENT, INCLUDING, WITHOUT LIMITATION, ANY BACK-UP EXPENSES, COSTS INCURRED FOR THE USE OF THE PRE-RELEASE SOFTWARE ON YOUR COMPUTER, DEVICES AND/OR PERIPHERALS, AND ANY DAMAGE TO ANY EQUIPMENT, SOFTWARE, INFORMATION OR DATA TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT WILL MYMDT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, WHETHER ARISING IN TORT (INCLUDING NEGLIGENCE), CONTRACT OR OTHERWISE, ARISING OUT OF OR RELATED TO THIS AGREEMENT, INCLUDING ANY LIABILITY THAT STEMS FROM ANY USE OF THE PRE-RELEASE SOFTWARE ON YOUR COMPUTER, DEVICES AND/OR ANY PERIPHERALS CONNECTED THERETO, AND/OR FROM ANY OTHER CONFIDENTIAL INFORMATION, AND/OR MYMDT’S PERFORMANCE OR FAILURE TO PERFORM UNDER THIS AGREEMENT, EVEN IF MYMDT HAS BEEN ADVISED OR IS AWARE OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL MYMDT'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES (OTHER THAN AS MAY BE REQUIRED BY APPLICABLE LAW IN CASES INVOLVING PERSONAL INJURY) EXCEED THE AMOUNT OF FIFTY DOLLARS ($50.00). THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. 

      13. Term and Termination. This Agreement will continue in effect until terminated in accordance with this Section 13. You may terminate this Agreement or an individual seeding project at any time, for any reason, but only by returning or destroying any Confidential Information that is in your possession or control (including, without limitation, any Pre-Release Software); provided however that if you are unable to purge certain Pre-Release Software from your computer and/or devices, then you agree that you will continue to hold the PreRelease Software as Confidential Information. MYMDT may terminate this Agreement or an individual seeding project at any time, with or without cause, immediately upon written notice to you, and may terminate this Agreement immediately for any breach of the confidentiality provisions set forth herein. Within seven (7) days of your receipt of MYMDT’s termination notice, or earlier if requested by MYMDT, you will return, cease all use of, and/or destroy the PreRelease Software and all other Confidential Information as provided in this Section. Following termination of this Agreement or an individual seeding project for any reason, the restrictions of Section 3, 4-8, the last two sentences of Section 9, and 11-19, inclusive, will continue to bind the parties.

      14. No Export. You agree that you will not export or re-export any of the PreRelease Software or Confidential Information received from MYMDT except as authorized by Singapore law and the laws of the jurisdiction in which the MYMDT Software was obtained.

      15. Third Party Software & Information. Portions of the MYMDT Software may respective vendor or supplier, and MYMDT shall have no responsibility with regard to the selection, performance, or use of these vendors or products. All understandings, agreements, or warranties, if any, take place directly between the vendors and the prospective users. 

      16. No Waiver or Assignment. No delay or failure to take action under this Agreement will constitute a waiver unless expressly waived in writing, signed by a duly authorized representative of MYMDT, and no single waiver will constitute a continuing or subsequent waiver. This Agreement may not be assigned by you in whole or in part. Any contrary assignment shall be null and void. 

      17. Governing Law. This Agreement will be governed by and construed in accordance with the laws of Singapore, as applied to agreements entered into and to be performed entirely within Singapore. 

      18. In the MYMDT software program, users will be allocated with a certain amount of MDT currency according to their engagement within the program.

      MDT is issued by Measurable Foundation Ltd, a public company limited by guarantee registered in Singapore, and approved and registered by Singapore Accounting and Corporate Regulatory Authority (ACRA). The Measurable foundation is meant to develop and promote the MDT ecosystem and will dedicate its resources in Research, Development and Governance. 

      MDT is a utility token and is not supposed to have any particular value
      outside the MDT ecosystem.  Since MDT is not a security token, this Whitepaper cannot constitute a prospectus or offer document for any investment in securities. 

      MDT (i) shall not provide you with rights of any form with respect to Company or its revenues or assets, including, but not limited to, any voting, distribution, redemption, liquidation, proprietary (including all forms of intellectual property), or other financial or legal rights; (ii) shall not be deemed to be a loan to Company; and (iii) shall not provide you with any ownership or other interest in the Company.

      Measurable Foundation warns that the involvement of purchasing any tokens represents a very high risk to any participating contributor. Activity should only be undertaken by those with substantial technical knowledge and that are also able to understand the specific network and related token being offered. Measurable Foundation Ltd, as well as its partners, team, directors, agents, joint ventures, employees and suppliers, assumes no liability or responsibility for any loss arising out of or related to the use of the MDT ecosystem or any technical, interruption or malfunction of the platform.

      19. Severability; Complete Understanding. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement, including any appendices made effective pursuant to this Agreement and any additional licenses accompanying the MYMDT Software, constitutes the entire agreement with respect to the Confidential Information disclosed herein and supersedes all prior or contemporaneous oral or written agreements concerning such Confidential Information. Except to the extent provided under Section 2 above, any inconsistencies between this Agreement and any license agreement accompanying the MYMDT Software will be governed by the license agreement accompanying the MYMDT Software. Except as expressly set forth herein, any waiver or amendment of any provision of this Agreement shall be effective only if in writing and signed by authorized representatives of both parties. Any translation of this Agreement is done for local requirements and in the event of a dispute between the English and any non-English versions, the English version of this Agreement shall govern, to the extent not prohibited by local law in your jurisdiction. 

    </p>
  </section>
</template>

<script>
import BasePage from '@/screens/BasePage';

export default {
  extends: BasePage,
  metaInfo() {
    return {
      title: this.$t('message.settings.termsOfUse'),
    };
  },
};
</script>

<style lang="scss" scoped>
.terms-of-use-screen {
  text-align: left;
  padding: 0 $defaultPageMargin $defaultPageMargin $defaultPageMargin;

  > p {
    white-space: pre-line;
    width: 100%;
  }
}
</style>
